branches:
  only:
    - master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Qt Creator 4.7.2

install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  
build: false
  
build_script:
  - qmake filesystem.pro
  - mingw32-make

artifacts:
  - path: Output\filesystem-*.exe
  - path: release
    type: zip
